---

- name: make sure apt is updated
  apt: name=apt state=latest

- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  sudo: yes
  #apt_repository: repo='ppa:webupd8team/java'
  shell: apt-add-repository ppa:webupd8team/java

- name: fix for debian
  shell: echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" > /etc/apt/sources.list.d/webupd8team-java-jessie.list
  when: ansible_distribution == 'Debian'

- name: update packages
  apt: update-cache=true

- name: Accept Java 8 License
  sudo: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  sudo: yes
  apt: name={{item}} state=latest
  with_items:
  - oracle-java8-installer
  - ca-certificates
  - oracle-java8-set-default

- name: Download Scala
  get_url: url=http://www.scala-lang.org/files/archive/scala-{{ scala_version }}.deb
       dest="/tmp/scala-{{ scala_version }}.deb"

- name: Extract and install Scala
  apt: deb=/tmp/scala-{{ scala_version }}.deb
  

#- name: Symlink Scala into /usr/local/bin
#  file: src=/opt/scala-{{ scala_version }}/bin/{{ item }}
#        dest=/usr/local/bin/{{ item }}
#        state=link
#  with_items:
#    - fsc
#    - scala
#    - scalac
#    - scaladoc
#    - scalap

#- name: Download SBT package
#  get_url: url=https://dl.bintray.com/sbt/debian/sbt-{{ scala_sbt_version }}.deb
#           dest=/usr/local/src/sbt-{{ scala_sbt_version }}.deb

#- name: Install SBT
#  apt: deb=/usr/local/src/sbt-{{ scala_sbt_version }}.deb
#       state=installed
