- hosts: allservers
  tasks:
  - name: yum
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - kubernetes
    - docker

- hosts: allservers
  tasks:
  - name: enable docker
    systemd:
     enabled: yes
     name: docker
  - name: restart docker
    systemd:
     state: restarted
     daemon_reload: yes
     name: docker
