- hosts: allservers
  remote_user: root
  tasks:
  - name: Add google's repos for k8s
    copy:
     content: "[kubernetes]\nname=Kubernetes\nbaseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
     dest: /etc/yum.repos.d/kubernetes.repo

- hosts: allservers
  tasks:
  - name: yum
    yum:
      name: "{{ item }}"
      state: removed
    with_items:
    - kubernetes
    - kubernetes-node
    - kubernetes-client

- hosts: allservers
  tasks:
  - name: yum
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - docker
    - kubelet 
    - kubeadm 
    - kubectl

- hosts: allservers
  tasks:
  - name: enable docker
    systemd:
     enabled: yes
     name: docker
  - name: restart docker
    systemd:
     state: restarted
     daemon_reload: yes
     name: docker

- hosts: gateways
  tasks:
  - name: enable kubelet
    systemd:
     enabled: yes
     name: kubelet
  - name: restart kubelet
    systemd:
     state: restarted
     daemon_reload: yes
     name: kubelet

