pipeline {
    agent { label 'master' }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                script {
                  RESULT = sh(returnStdout: true, script: 'ansible-playbook -v ./linux/centos/8/web-server-with-webmin/01-basic-software.yml --user root --key-file /root/.ssh/id_rsa')
                }
                echo "${RESULT}"
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                script {
                  RESULT = sh(returnStdout: true, script: 'ansible-playbook -v ./linux/centos/8/web-server-with-webmin/02-install-webmin.yml --user root --key-file /root/.ssh/id_rsa')
                }
                echo "${RESULT}"
            }
        }
    }
}
